#!/usr/bin/env python3
from collections import Counter, defaultdict
import sys
from cs4041.review import read_reviews
from cs4041.vocabulary import (get_combined_frequencies,
                               get_vocabulary_from_frequencies,
                               write_vocabulary)

VOCABULARY_FNAME = "data/bigram_vocabulary.txt"


def main():
    if len(sys.argv) < 2:
        print('usage: {} processed_datafile'.format(sys.argv[0]),
              file=sys.stderr)
        sys.exit(1)

    frequency = defaultdict(Counter)

    cleaned_reviews = read_reviews(sys.argv[1])

    for class_, review_list in cleaned_reviews.items():
        frequency[class_] = get_combined_frequencies(review_list)

    vocabulary = get_vocabulary_from_frequencies(
        [frequency[class_] for class_ in cleaned_reviews.keys()],
        min_occur=3)

    write_vocabulary(vocabulary, VOCABULARY_FNAME)


if __name__ == '__main__':
    main()
